//! Async log-wait helpers for tests that use `#[tracing_test::traced_test]`.
//!
//! `logs_contain` is a synchronous snapshot of the log buffer generated by
//! the `traced_test` macro. Use `wait_for_log` to poll that predicate until
//! it becomes true or a deadline expires — the preferred replacement for
//! `tokio::time::sleep(X).await` setup fences whose only purpose is "give
//! the background task a moment to reach state Y". The log is the
//! authoritative signal that state Y was reached.

use std::time::Duration;

/// Poll `predicate` every 10 ms until it returns `true` or `timeout` elapses.
/// Panics with `msg` on timeout. Returns immediately once the predicate is
/// satisfied, so tests spend the minimum time needed on setup.
///
/// Call site pattern:
/// ```ignore
/// wait_for_log(
///     || logs_contain("broker dial failed"),
///     Duration::from_secs(2),
///     "dialer never failed",
/// ).await;
/// ```
pub async fn wait_for_log<F>(predicate: F, timeout: Duration, msg: &str)
where
    F: Fn() -> bool,
{
    let deadline = tokio::time::Instant::now() + timeout;
    loop {
        if predicate() {
            return;
        }
        if tokio::time::Instant::now() >= deadline {
            panic!("timed out waiting for log: {msg}");
        }
        tokio::time::sleep(Duration::from_millis(10)).await;
    }
}
